# ===============================================================
# 全局训练配置 (Global Training Settings)
# ===============================================================
model_settings:
  name: "Geo_localGT"
  pretrain_ckpt: "ckpt/best_transformer_places2.pth"
  tb_images: True
  tb_max_images: 5
  tb_logdir: "/root/tf-logs/"

training_params:
  lr: 1e-4
  train_epoch: 100
  seq_batch: 80
  num_workers: 6
  prefetch_factor: 2
  AMP: True
  MaP: True
  focal_weight: 1.0
  tversky_weight: 1.0
  line_tv_alpha: 0.4
  line_tv_beta: 0.6
  dilate1_ep: 30
  disable_edge: True
  accumulation_steps: 2  # 梯度累积补偿小 batch
  no_align: True

# ===============================================================
# 数据集 1: DL3DV
# ===============================================================
dataset1:
  enable: True
  name: "DL3DV"
  ratio: 1
  train_imgs_list: "data_list/DL3DV1K_imgs_train.txt"
  train_pkls_list: "data_list/DL3DV1K_pkls_train.txt"
  train_npzs_list: "data_list/DL3DV1K_npzs_train.txt"

  val_imgs_list: "data_list/DL3DV10K_imgs_val.txt"
  val_pkls_list: "data_list/DL3DV10K_pkls_val.txt"
  val_npzs_list: "data_list/DL3DV10K_npzs_val.txt"

# ===============================================================
# 数据集 2: ScannetPP
# ===============================================================
dataset2:
  enable: False
  name: "ScannetPP"
  ratio: 1
  train_imgs_list: ""
  train_pkls_list: ""
  train_npzs_list: ""

  val_imgs_list: ""
  val_pkls_list: ""
  val_npzs_list: ""


# ===============================================================
# 掩码配置 (全局共用)
# ===============================================================
masks:
  train_mask_list: "/root/autodl-tmp/Inpainting/SfM_inpainting/data_list/irregular_mask_40_50.txt"
  val_mask_list: "/root/autodl-tmp/Inpainting/SfM_inpainting/data_list/irregular_mask_30_40.txt"